// <auto-generated />
using System;
using CapyCard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapyCard.Migrations
{
    [DbContext(typeof(FlashcardDbContext))]
    [Migration("20251125112001_AddSmartLearningMode")]
    partial class AddSmartLearningMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CapyCard.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("CapyCard.Models.CardSmartScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardSmartScores");
                });

            modelBuilder.Entity("CapyCard.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRandomOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastLearnedCardIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearnedShuffleCardIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentDeckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentDeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("CapyCard.Models.LearningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastLearnedIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearnedCardIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedDeckIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("CapyCard.Models.Card", b =>
                {
                    b.HasOne("CapyCard.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("CapyCard.Models.CardSmartScore", b =>
                {
                    b.HasOne("CapyCard.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("CapyCard.Models.Deck", b =>
                {
                    b.HasOne("CapyCard.Models.Deck", "ParentDeck")
                        .WithMany("SubDecks")
                        .HasForeignKey("ParentDeckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentDeck");
                });

            modelBuilder.Entity("CapyCard.Models.LearningSession", b =>
                {
                    b.HasOne("CapyCard.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("CapyCard.Models.Deck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("SubDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
